addReviewers: true

addAssignees: false

reviewers:
  - smaranjitghose
  - anushbhatia
  - sukkritsharmaofficial

# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

skipKeywords:
  - wip
