name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening an issue! Kindly note that this repository is maintained by [Smaranjit Ghose](https://https://github.com/smaranjitghose/). He will get back to you soon. '' first issue'
        pr-message: 'Thanks for opening this pull request! Kindly wait for the maintainers to review it.'' first pr'
